#!/bin/bash

echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║     🚀 小勋象棋 - GitHub自动上传和编译                    ║"
echo "║                                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Git仓库已初始化"
echo "✓ 代码已提交"
echo "✓ 分支已设置为main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 接下来需要你的GitHub信息:"
echo ""

# 获取GitHub用户名
read -p "请输入你的GitHub用户名: " GITHUB_USERNAME

if [ -z "$GITHUB_USERNAME" ]; then
    echo "❌ 用户名不能为空"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 第一步: 在GitHub上创建仓库"
echo ""
echo "请按以下步骤操作:"
echo ""
echo "1. 访问: https://github.com/new"
echo "2. Repository name: xiaoxun-xiangqi"
echo "3. Description: 小勋象棋 - 中国象棋Android应用（带AI对手）"
echo "4. 选择 Public 或 Private"
echo "5. ❌ 不要勾选 \"Initialize this repository with a README\""
echo "6. 点击 \"Create repository\""
echo ""
read -p "完成后按回车继续..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔐 第二步: 准备认证"
echo ""
echo "推送时需要Personal Access Token (不是GitHub密码)"
echo ""
echo "获取Token:"
echo "1. 访问: https://github.com/settings/tokens/new"
echo "2. Note: xiaoxun-xiangqi"
echo "3. Expiration: 90 days"
echo "4. 勾选: repo (所有权限)"
echo "5. 点击 \"Generate token\""
echo "6. 复制token (只显示一次!)"
echo ""
read -p "准备好Token后按回车继续..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 第三步: 推送代码"
echo ""

# 设置远程仓库
REMOTE_URL="https://github.com/$GITHUB_USERNAME/xiaoxun-xiangqi.git"
git remote add origin "$REMOTE_URL" 2>/dev/null || git remote set-url origin "$REMOTE_URL"

echo "远程仓库: $REMOTE_URL"
echo ""
echo "正在推送..."
echo ""

if git push -u origin main; then
    echo ""
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║                                                          ║"
    echo "║              ✅ 上传成功！                                ║"
    echo "║                                                          ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo ""
    echo "🎉 GitHub Actions正在自动编译APK..."
    echo ""
    echo "📍 查看编译进度:"
    echo "   https://github.com/$GITHUB_USERNAME/xiaoxun-xiangqi/actions"
    echo ""
    echo "⏱️  编译时间: 约3-5分钟"
    echo ""
    echo "📥 编译完成后下载APK:"
    echo "   1. 点击最新的workflow运行记录（绿色✓）"
    echo "   2. 向下滚动到 \"Artifacts\" 区域"
    echo "   3. 下载 xiaoxun-xiangqi-debug.zip"
    echo "   4. 解压得到APK文件"
    echo ""
    echo "🎊 完成！"
    echo ""
else
    echo ""
    echo "❌ 推送失败"
    echo ""
    echo "常见原因:"
    echo "• GitHub仓库未创建"
    echo "• Token错误（使用Token而不是密码）"
    echo "• 网络问题"
    echo ""
    echo "解决方法:"
    echo "1. 确认已创建GitHub仓库"
    echo "2. 使用Personal Access Token作为密码"
    echo "3. 检查网络连接"
    echo ""
fi
